# Generated by Django 5.1.3 on 2024-12-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_json',
            field=models.CharField(blank=True, max_length=50000),
        ),
    ]
